spring:
    datasource:
        name: jajmeup
        url: jdbc:mysql://localhost:3306/jajmeup
        username: jajmeup
        password: ra4Y75UkG8X1N21j
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect