spring:
    datasource:
        name: [NAME_TEST]
        url: jdbc:mysql://localhost:3306/[NAME_TEST]
        username: [USERNAME]
        password: [PASSWORD]
    jpa:
        hibernate:
            ddl-auto: none
jajmeup:
    security:
        secret-key: secret-key-test