spring:
    datasource:
        name: [NAME]
        url: jdbc:mysql://localhost:3306/[NAME]
        username: [USERNAME]
        password: [PASSWORD]
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect